services:
  website:
    build: .
    image: vidpravki
    restart: always
    container_name: vidpravki
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vidpravki.rule=Host(`${HOST}`)"
      - "traefik.http.routers.vidpravki.entrypoints=websecure"
      - "traefik.http.routers.vidpravki.tls.certresolver=myresolver"
      - "traefik.http.services.vidpravki.loadbalancer.server.port=3914"

    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
